---
Standards:
  - Title: Practice Block
    UID: e2039bd2-3ff3-4d8f-95bd-f2eb4bce4f06
    Description: Learn how to contirbute to curriculum on GitHub
    SuccessCriteria:
      - Successfully adds or edits a file and sees the changes in Learn
    ContentFiles:
      - Type: Lesson
        UID: dc749ef8-457e-11ed-b878-0242ac120002
        Path: /joseph-martin.md
      - Type: Lesson
        UID: 2916d421-b4e4-4a47-bcc0-bdd1b5e1c0f4
        Path: /kevin-goble.md
